name = "codex-version-check-prode"
main = "src/index.ts"
compatibility_date = "2026-07-04"

[vars]
GITHUB_OWNER = "zats"
GITHUB_REPO = "bibliotheca"
GITHUB_BRANCH = "main"
GITHUB_WORKFLOW_ID = "codex-version-watch.yml"

[triggers]
crons = ["*/5 * * * *"]
